modLoader = "javafml"
loaderVersion = "[51,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "ue-cosmetics"
version = "${version}"
displayName = "ueCosmetics"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.ue-cosmetics]]
modId = "forge"
mandatory = true
versionRange = "[51,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ue-cosmetics]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"
